#开发配置
spring:
  datasource:
      #url: jdbc:mysql://127.0.0.1:3306/htgl?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&characterEncoding=utf8
      url: jdbc:mysql://121.196.185.230:3306/htgl?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.ropz.htgl.entity
  mapperLocations: classpath:mapper/*.xml

